export const stages = [
  "Zavod",
  "Anbardadır",
  "Yoldadır",
  "Hazırdır",
  "Təhvilə çıxıb",
  "Təhvil verilib",
];

export const navItems = [
  { id: "dashboard", label: "Panel" },
  { id: "crm", label: "CRM" },
  { id: "sales", label: "Satış" },
  { id: "warehouse", label: "Anbar" },
  { id: "deliveries", label: "Təhvil" },
  { id: "finance", label: "Maliyyə" },
  { id: "invoices", label: "Fakturalar" },
  { id: "accounting", label: "Mühasibat" },
  { id: "tax", label: "Vergi" },
  { id: "credits", label: "Kreditlər" },
  { id: "receivables", label: "Borclar" },
  { id: "vendors", label: "Vendorlar" },
  { id: "projects", label: "ROI" },
  { id: "production", label: "İstehsalat" },
  { id: "hr", label: "HR" },
  { id: "kpi", label: "KPI" },
  { id: "contracts", label: "Müqavilələr" },
  { id: "reports", label: "Hesabatlar" },
  { id: "support", label: "Dəstək" },
  { id: "help", label: "Kömək" },
  { id: "onboarding", label: "Onboarding" },
  { id: "messages", label: "Mesajlar" },
  { id: "notifications", label: "Bildirişlər" },
  { id: "api", label: "API" },
  { id: "settings", label: "Ayarlar" },
];

export const initialState = {
  customers: [],
  products: [],
  orders: [],
  stock: [],
  warehouses: [],
  warehouseStock: {},
  expenses: [],
  cashEntries: [],
  financeAccounts: [],
  credits: [],
  vendors: [],
  employees: [],
  departments: [],
  leaveRequests: [],
  vacancies: [],
  contracts: [],
  notifications: [],
  conversations: [],
  notificationRules: [],
  projects: [],
  productionPlans: [],
  supportTickets: [],
  knowledgeBase: [],
  taxCalendar: [],
  currencyRates: [],
  apiWebhooks: [],
  purchaseOrders: [],
  auditLog: [],
  reportExports: [],
  accountingClose: null,
  receivableSync: null,
  notificationSweepAt: null,
  integritySnapshot: null,
  goLiveSnapshot: null,
  onboarding: {
    companyStage: "İlkin qurulum",
    businessArea: "",
    employeeCount: "",
    steps: [
      { id: "ONB-1", title: "Şirkət məlumatlarını daxil edin", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-2", title: "İlk anbarı yaradın", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-3", title: "Məhsul kataloqunu və ilkin mədaxili yaradın", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-4", title: "İstifadəçi və rolları təyin edin", owner: "Administrator", status: "Gözləyir" },
      { id: "ONB-5", title: "Kassa və bank açılış balanslarını daxil edin", owner: "Maliyyə", status: "Gözləyir" },
      { id: "ONB-6", title: "Əməkdaş məlumatlarını daxil edin", owner: "HR", status: "Gözləyir" },
    ],
  },
  invoiceSettings: {
    prefix: "EQ",
    vatRate: 18,
    paymentTermsDays: 7,
    eTaxMode: "E-qaimə inteqrasiya rejimi",
    defaultCurrency: "AZN",
  },
  settings: {
    company: "",
    voen: "",
    phone: "",
    email: "",
    address: "",
    toggles: {
      push: true,
      sms: true,
      email: false,
      creditWarnings: true,
      lowStock: true,
    },
    sessionUserId: "USR-ADMIN",
    users: [
      {
        id: "USR-ADMIN",
        name: "Administrator",
        email: "admin@local",
        role: "Super Admin",
        status: "Aktiv",
      },
    ],
  },
};

export const reportTemplates = [
  { title: "Aylıq satış hesabatı", desc: "Satış, məhsul və satıcı üzrə icmal", cadence: "Aylıq" },
  { title: "Maliyyə mənfəət/zərər", desc: "Gəlir, xərc və net nəticə", cadence: "Aylıq" },
  { title: "Anbar hərəkəti", desc: "Mədaxil, rezerv, təhvil və qalığa baxış", cadence: "Həftəlik" },
  { title: "Kredit portfeli", desc: "Aktiv, gecikən və bağlanan kreditlər", cadence: "Gündəlik" },
];

export const goals = [];

export const contractTemplates = [
  { title: "Satış müqaviləsi", desc: "Müştəri, məhsul və qiymət avtomatik doldurulur" },
  { title: "Kredit satış müqaviləsi", desc: "Aylıq ödəniş cədvəli əlavə olunur" },
  { title: "Topdan satış müqaviləsi", desc: "Çoxsaylı məhsul və endirim sxemi" },
  { title: "Xidmət müqaviləsi", desc: "Servis şərtləri və zəmanət" },
];
